---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    wego.weave.works/app-identifier: wego-7fddf5ce311580ddbe92edccddbc52ad
  name: podinfo-deploy
  namespace: wego-system
spec:
  branch: main
  deployment_type: kustomize
  path: ./
  source_type: git
  url: ssh://git@github.com/JasonMorgan/podinfo-deploy.git
